"""add abstract and keywords

Revision ID: c820dc8d8ba3
Revises: 29d562a5b4ea
Create Date: 2026-07-30 10:32:48.175719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c820dc8d8ba3'
down_revision: Union[str, Sequence[str], None] = '29d562a5b4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('abstract', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('keywords', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'keywords')
    op.drop_column('articles', 'abstract')
    # ### end Alembic commands ###
