"""scopus_author_id, scopus_affiliation_id, unit, sync_log ekle

Revision ID: 0a8ddd32f1cf
Revises: 9b52e703be37
Create Date: 2026-07-31 11:15:46.973194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8ddd32f1cf'
down_revision: Union[str, Sequence[str], None] = '9b52e703be37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_log_id'), 'sync_log', ['id'], unique=False)
    op.add_column('authors', sa.Column('scopus_author_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_authors_auth_fullname'), table_name='authors')
    op.create_index(op.f('ix_authors_auth_fullname'), 'authors', ['auth_fullname'], unique=False)
    op.create_index(op.f('ix_authors_scopus_author_id'), 'authors', ['scopus_author_id'], unique=True)
    op.add_column('institutions', sa.Column('scopus_affiliation_id', sa.String(), nullable=True))
    op.add_column('institutions', sa.Column('unit', sa.String(), nullable=True))
    op.create_index(op.f('ix_institutions_scopus_affiliation_id'), 'institutions', ['scopus_affiliation_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institutions_scopus_affiliation_id'), table_name='institutions')
    op.drop_column('institutions', 'unit')
    op.drop_column('institutions', 'scopus_affiliation_id')
    op.drop_index(op.f('ix_authors_scopus_author_id'), table_name='authors')
    op.drop_index(op.f('ix_authors_auth_fullname'), table_name='authors')
    op.create_index(op.f('ix_authors_auth_fullname'), 'authors', ['auth_fullname'], unique=True)
    op.drop_column('authors', 'scopus_author_id')
    op.drop_index(op.f('ix_sync_log_id'), table_name='sync_log')
    op.drop_table('sync_log')
    # ### end Alembic commands ###
